#!/usr/bin/env bash
set -e

echo ">>> run_autograder: start"
cd /autograder/submission

# run grader
Rscript /autograder/source/grade.R

#
if [ -f results.json ]; then
  mv results.json /autograder/results/results.json
fi

echo ">>> done"
