#!/usr/bin/env bash
set -euo pipefail
echo ">>> run_autograder: start"

echo ">>> ensure results dir"
mkdir -p /autograder/results

echo ">>> copy student submission"
cp /autograder/submission/HW06_TidyPart02.R /autograder/source/HW06_TidyPart02.R

cd /autograder/source

echo ">>> run Rscript"
LC_ALL= Rscript grade.R || true

echo ">>> run_autograder: done"
