name: build-and-push
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          test -n "${{ secrets.DOCKER_USER }}" || (echo "Missing DOCKER_USER" && exit 1)
          test -n "${{ secrets.DOCKER_PAT }}"  || (echo "Missing DOCKER_PAT" && exit 1)

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            xhnnnnn/gs-autograder:hw7
